apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-engine
  namespace: legend
spec:
  replicas: 2  # Higher replicas for production
  template:
    spec:
      containers:
      - name: legend-engine
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-sdlc
  namespace: legend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: legend-sdlc
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"