apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oauth
  namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  GITLAB_APP_ID: "${GITLAB_APP_ID_BASE64}"
  GITLAB_APP_SECRET: "${GITLAB_APP_SECRET_BASE64}"
  GITLAB_HOST: "${GITLAB_HOST_BASE64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  MONGODB_USER: "${MONGODB_USER_BASE64}"
  MONGODB_PASSWORD: "${MONGODB_PASSWORD_BASE64}"
  MONGODB_NAME: "${MONGODB_NAME_BASE64}"
