services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: legend-traefik
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --serversTransport.insecureSkipVerify=true
      - --api.dashboard=true
      - --api.insecure=true            # dev only
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"                    # dashboard
    networks:
      - default
      - legend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  legend-studio:
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.studio.rule=Host(`dev.atheryon.ai`) && PathPrefix(`/studio`)
      - traefik.http.services.studio.loadbalancer.server.port=9000
      - traefik.docker.network=${COMPOSE_PROJECT_NAME:-legend}_default
      - traefik.http.routers.studio.entrypoints=web
  legend-sdlc:
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.sdlc.rule=Host(`dev.atheryon.ai`) && PathPrefix(`/sdlc`)
      - traefik.http.middlewares.sdlc-strip.stripprefix.prefixes=/sdlc
      - traefik.http.routers.sdlc.middlewares=sdlc-strip
      - traefik.http.services.sdlc.loadbalancer.server.port=6100
      - traefik.docker.network=${COMPOSE_PROJECT_NAME:-legend}_default
      - traefik.http.routers.sdlc.entrypoints=web

  legend-engine:
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.engine.rule=Host(`dev.atheryon.ai`) && PathPrefix(`/engine`)
      - traefik.http.middlewares.engine-strip.stripprefix.prefixes=/engine
      - traefik.http.routers.engine.middlewares=engine-strip
      - traefik.http.services.engine.loadbalancer.server.port=6300
      - traefik.docker.network=${COMPOSE_PROJECT_NAME:-legend}_default
      - traefik.http.routers.engine.entrypoints=web

  legend-depot:
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.depot.rule=Host(`dev.atheryon.ai`) && PathPrefix(`/depot`)
      - traefik.http.middlewares.depot-strip.stripprefix.prefixes=/depot
      - traefik.http.routers.depot.middlewares=depot-strip
      - traefik.http.services.depot.loadbalancer.server.port=6200
      - traefik.docker.network=${COMPOSE_PROJECT_NAME:-legend}_default
      - traefik.http.routers.depot.entrypoints=web


