#!/bin/bash

# Fix GitLab OAuth Redirect URI Issue
# This script documents the necessary configuration for GitLab OAuth

echo "========================================="
echo "GitLab OAuth Configuration Fix"
echo "========================================="
echo ""
echo "The error 'The redirect URI included is not valid' occurs because"
echo "the redirect URI being used by Legend Studio doesn't match what's"
echo "configured in your GitLab OAuth application."
echo ""
echo "Current redirect URI being used:"
echo "  http://dev.atheryon.ai:9000/studio/log.in/callback?client_name=gitlab"
echo ""
echo "========================================="
echo "REQUIRED ACTION:"
echo "========================================="
echo ""
echo "1. Go to GitLab OAuth Application Settings:"
echo "   https://gitlab.com/-/profile/applications"
echo ""
echo "2. Find your application with ID:"
echo "   dbdd707e51066b5b948d238bb0f84b7a7d2c883e008671c7dc33c1c5c639c862"
echo ""
echo "3. Click 'Edit' and add these Redirect URIs:"
echo ""
echo "   Primary (with port - currently being used):"
echo "   http://dev.atheryon.ai:9000/studio/log.in/callback"
echo ""
echo "   Alternative URIs (for different access methods):"
echo "   http://dev.atheryon.ai/studio/log.in/callback"
echo "   https://dev.atheryon.ai/studio/log.in/callback"
echo "   http://localhost:9000/studio/log.in/callback"
echo "   http://localhost:6100/api/auth/callback"
echo ""
echo "4. Ensure these scopes are selected:"
echo "   - api"
echo "   - openid"
echo "   - profile"
echo ""
echo "5. Save the application"
echo ""
echo "========================================="
echo "ALTERNATIVE SOLUTION:"
echo "========================================="
echo ""
echo "If you cannot modify the GitLab application, access Legend Studio"
echo "without the port number using the reverse proxy:"
echo ""
echo "1. Configure reverse proxy to strip port from URLs"
echo "2. Access at: http://dev.atheryon.ai/studio"
echo "   (without :9000)"
echo ""
echo "========================================="
echo "VERIFICATION:"
echo "========================================="
echo ""
echo "After updating GitLab OAuth application:"
echo "1. Clear browser cookies/cache"
echo "2. Try accessing Legend Studio again"
echo "3. The OAuth flow should complete successfully"
echo ""
echo "Current environment variables in use:"
echo "GITLAB_HOST=${GITLAB_HOST:-gitlab.com}"
echo "GITLAB_APP_ID=dbdd707e51066b5b948d238bb0f84b7a7d2c883e008671c7dc33c1c5c639c862"
echo ""