apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-guardian-agent
  namespace: ${K8S_NAMESPACE}
  labels:
    app: legend-guardian-agent
    component: guardian
spec:
  replicas: ${GUARDIAN_REPLICAS:-1}
  selector:
    matchLabels:
      app: legend-guardian-agent
  template:
    metadata:
      labels:
        app: legend-guardian-agent
        component: guardian
    spec:
      containers:
      - name: legend-guardian-agent
        image: ${GUARDIAN_IMAGE:-legend-guardian-agent:latest}
        ports:
        - containerPort: ${GUARDIAN_PORT}
        env:
        - name: LEGEND_ENGINE_URL
          value: "${LEGEND_ENGINE_URL}"
        - name: LEGEND_SDLC_URL
          value: "${LEGEND_SDLC_URL}"
        - name: LEGEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: guardian-secrets
              key: LEGEND_API_KEY
        - name: LEGEND_API_HOST
          value: "${GUARDIAN_API_HOST}"
        - name: LEGEND_API_PORT
          value: "${GUARDIAN_API_PORT}"
        - name: LEGEND_LOG_LEVEL
          value: "${LOG_LEVEL}"
        - name: NODE_ENV
          value: "${NODE_ENV}"
        resources:
          requests:
            memory: "${GUARDIAN_MEMORY_REQUEST}"
            cpu: "${GUARDIAN_CPU_REQUEST}"
          limits:
            memory: "${GUARDIAN_MEMORY_LIMIT}"
            cpu: "${GUARDIAN_CPU_LIMIT}"
        livenessProbe:
          httpGet:
            path: ${GUARDIAN_LIVENESS_PROBE_PATH}
            port: ${GUARDIAN_PORT}
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: ${GUARDIAN_READINESS_PROBE_PATH}
            port: ${GUARDIAN_PORT}
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: legend-guardian-agent
  namespace: ${K8S_NAMESPACE}
  labels:
    app: legend-guardian-agent
spec:
  type: ClusterIP
  ports:
  - port: ${GUARDIAN_PORT}
    targetPort: ${GUARDIAN_PORT}
    protocol: TCP
    name: http
  selector:
    app: legend-guardian-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: guardian-secrets
  namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  LEGEND_API_KEY: "${LEGEND_API_KEY_BASE64}"
