apiVersion: v1
kind: Secret
metadata:
  name: legend-guardian-secrets
  namespace: legend-guardian
  labels:
    app: legend-guardian
type: Opaque
stringData:
  database-url: "postgresql://legend:legend@postgres:5432/legend"
  api-key: "demo-key"
  engine-token: ""
  sdlc-token: ""
  depot-token: ""
---
# Azure Key Vault CSI Driver SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: legend-guardian-azure-keyvault
  namespace: legend-guardian
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<IDENTITY_CLIENT_ID>"
    keyvaultName: "<KEY_VAULT_NAME>"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: api-key
          objectType: secret
          objectAlias: API_KEY
        - |
          objectName: engine-token
          objectType: secret
          objectAlias: ENGINE_TOKEN
        - |
          objectName: sdlc-token
          objectType: secret
          objectAlias: SDLC_TOKEN
        - |
          objectName: depot-token
          objectType: secret
          objectAlias: DEPOT_TOKEN
        - |
          objectName: valid-api-keys
          objectType: secret
          objectAlias: VALID_API_KEYS
    tenantId: "<AZURE_TENANT_ID>"
  secretObjects:
  - secretName: legend-guardian-secrets-synced
    type: Opaque
    data:
    - objectName: DATABASE_URL
      key: database-url
    - objectName: API_KEY
      key: api-key
    - objectName: ENGINE_TOKEN
      key: engine-token
    - objectName: SDLC_TOKEN
      key: sdlc-token
    - objectName: DEPOT_TOKEN
      key: depot-token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: legend-guardian-config
  namespace: legend-guardian
  labels:
    app: legend-guardian
data:
  app-config.yaml: |
    app:
      name: Legend Guardian Agent
      version: 1.0.0
      debug: false
    
    services:
      engine:
        url: http://legend-engine:6300
        timeout: 30
      sdlc:
        url: http://legend-sdlc:6100
        timeout: 30
      depot:
        url: http://legend-depot:6200
        timeout: 30
      studio:
        url: http://legend-studio:9000
        timeout: 30
    
    agent:
      model: gpt-4
      temperature: 0.7
      max_tokens: 2000
    
    rag:
      enabled: true
      chunk_size: 1000
      chunk_overlap: 200
      vector_store: chroma
    
    security:
      pii_redaction: true
      max_request_size: 10485760
    
    performance:
      request_timeout: 30
      max_retries: 3
      circuit_breaker_threshold: 5
    
    observability:
      otel_enabled: true
      otel_endpoint: http://otel-collector:4317
      log_level: INFO
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: legend-guardian
  labels:
    app: legend-guardian
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>