apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-studio
  namespace: legend-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legend-studio
  template:
    metadata:
      labels:
        app: legend-studio
    spec:
      containers:
      - name: legend-studio
        image: finos/legend-studio:3.0.0
        ports:
        - containerPort: 8080
        env:
        - name: LEGEND_STUDIO_PORT
          value: "8080"
        - name: LEGEND_STUDIO_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: legend-studio
  namespace: legend-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: legend-studio
