apiVersion: v1
kind: ConfigMap
metadata:
  name: legend-env
  namespace: legend
data:
  config.json: |
    {
      "sdlc": {
        "url": "http://legend-sdlc:6100/api"
      },
      "engine": {
        "url": "http://legend-engine:6300/api"
      },
      "depot": {
        "url": "https://legend.finos.org/depot/api"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-engine
  namespace: legend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legend-engine
  template:
    metadata:
      labels:
        app: legend-engine
    spec:
      containers:
      - name: legend-engine
        image: finos/legend-engine-server:4.25.1
        ports:
        - containerPort: 6300
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        command: ["/bin/sh"]
        args: ["-c", "java -cp /app/bin/*.jar -Dfile.encoding=UTF8 org.finos.legend.engine.server.Server server /config/config.yml || sleep 3600"]
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: legend-engine-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: legend-engine-config
  namespace: legend
data:
  config.yml: |
    server:
      applicationConnectors:
        - type: http
          port: 6300
      adminConnectors:
        - type: http
          port: 6301
    logging:
      level: INFO
    swagger:
      resourcePackage: org.finos.legend.engine.server.core
    pac4j:
      bypassPaths:
        - /api/server/v1/info
        - /api/swagger.json
      clients:
        - org.finos.legend.server.pac4j.gitlab.GitlabClient:
            name: gitlab
            clientId: not-configured
            secret: not-configured
            discoveryUri: https://gitlab.com/.well-known/openid-configuration
    metadata:
      pure:
        host: localhost
        port: 8090
        context: /
    stores: []
---
apiVersion: v1
kind: Service
metadata:
  name: legend-engine
  namespace: legend
spec:
  ports:
    - port: 6300
      targetPort: 6300
  selector:
    app: legend-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-studio-new
  namespace: legend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legend-studio-new
  template:
    metadata:
      labels:
        app: legend-studio-new
    spec:
      containers:
      - name: legend-studio
        image: finos/legend-studio:4.13.5
        ports:
        - containerPort: 8080
        env:
        - name: LEGEND_STUDIO_SDLC_SERVER_URL
          value: "http://legend-sdlc:6100"
        - name: LEGEND_STUDIO_ENGINE_SERVER_URL
          value: "http://legend-engine:6300"
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: config
        configMap:
          name: legend-env
---
apiVersion: v1
kind: Service
metadata:
  name: legend-studio-new
  namespace: legend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: legend-studio-new