---
# Legend Engine Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-engine
  namespace: ${K8S_NAMESPACE}
  labels:
    app: legend-engine
    component: engine
spec:
  replicas: ${ENGINE_REPLICAS:-2}
  selector:
    matchLabels:
      app: legend-engine
  template:
    metadata:
      labels:
        app: legend-engine
        component: engine
    spec:
      containers:
      - name: legend-engine
        image: finos/legend-engine-server:${LEGEND_ENGINE_VERSION}
        ports:
        - containerPort: ${LEGEND_ENGINE_PORT}
        env:
        - name: JAVA_OPTS
          value: "-Xmx${ENGINE_MEMORY_LIMIT} -Xms${ENGINE_MEMORY_REQUEST} -Dreflections.scan.disable=true -Dswagger.scan.disable=true"
        - name: LEGEND_ENGINE_URL
          value: "${LEGEND_ENGINE_URL}"
        - name: MONGODB_URI
          value: "${MONGODB_URI}"
        - name: MONGODB_NAME
          value: "${MONGODB_NAME}"
        - name: MONGO_SESSION_ENABLED
          value: "${MONGODB_SESSION_ENABLED:-false}"
        - name: MONGO_SESSION_STORE
          value: "${MONGODB_SESSION_STORE:-false}"
        - name: MONGO_SESSION_COLLECTION
          value: "${MONGODB_SESSION_COLLECTION:-sessions}"
        - name: ENGINE_PORT
          value: "${LEGEND_ENGINE_PORT}"
        - name: ENGINE_HOST
          value: "${LEGEND_ENGINE_HOST}"
        - name: METADATA_PURE_HOST
          value: "${METADATA_PURE_HOST}"
        - name: METADATA_PURE_PORT
          value: "${METADATA_PURE_PORT}"
        - name: METADATA_PURE_PATH
          value: "${METADATA_PURE_PATH}"
        - name: GITLAB_APP_ID
          value: "${GITLAB_APP_ID}"
        - name: GITLAB_APP_SECRET
          value: "${GITLAB_APP_SECRET}"
        - name: GITLAB_HOST
          value: "${GITLAB_HOST}"
        resources:
          requests:
            memory: "${ENGINE_MEMORY_REQUEST}"
            cpu: "${ENGINE_CPU_REQUEST}"
          limits:
            memory: "${ENGINE_MEMORY_LIMIT}"
            cpu: "${ENGINE_CPU_LIMIT}"
        livenessProbe:
          httpGet:
            path: ${ENGINE_LIVENESS_PROBE_PATH}
            port: ${LEGEND_ENGINE_PORT}
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: ${ENGINE_READINESS_PROBE_PATH}
            port: ${LEGEND_ENGINE_PORT}
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Legend Engine Service
apiVersion: v1
kind: Service
metadata:
  name: legend-engine
  namespace: ${K8S_NAMESPACE}
  labels:
    app: legend-engine
spec:
  type: ClusterIP
  ports:
  - port: ${LEGEND_ENGINE_PORT}
    targetPort: ${LEGEND_ENGINE_PORT}
    protocol: TCP
    name: http
  selector:
    app: legend-engine