server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 6100
  adminConnectors:
    - type: http
      port: 6101

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Minimal pac4j configuration to avoid startup NPEs when no IdP is configured
pac4j:
  bypassPaths:
    - "/api/health"
    - "/api/info"
  sessionTokenName: LegendSessionToken
  mongoSession:
    enabled: false
  clients: []
  authorizers: {}

mongodb:
  url: mongodb://mongodb.legend-system.svc.cluster.local:27017/legend
  database: legend
  sessionEnabled: false

gitlab:
  appId: "${GITLAB_APP_ID}"
  appSecret: "${GITLAB_APP_SECRET}"
  host: "${GITLAB_HOST}"

# Optional: baseline SDLC feature toggles to reduce external dependencies
features:
  canCreateProject: true
  canCreateVersion: true
