# Legend Engine Configuration for Local Development
# Complete configuration with all required fields

server:
  applicationConnectors:
    - type: http
      port: 6300
  adminConnectors:
    - type: http
      port: 6301

logging:
  level: INFO
  appenders:
    - type: console

# Swagger configuration (required)
swagger:
  resourcePackage: org.finos.legend.engine
  title: Legend Engine API
  version: 1.0.0

# Pac4j configuration (required)
pac4j:
  bypassPaths:
    - "/api/health"
    - "/api/server/info"
    - "/api/server/v1/info"
  sessionTokenName: LegendSessionToken
  mongoSession:
    enabled: false
  clients: []
  authorizers: []

# MongoDB configuration
mongodb:
  url: mongodb://admin:admin@mongodb:27017/legend?authSource=admin
  database: legend

# SDLC configuration
sdlc:
  url: http://legend-sdlc:6100