# Legend SDLC Configuration for Local Development
# Configured for GitLab integration

server:
  applicationConnectors:
    - type: http
      port: 6100
  adminConnectors:
    - type: http
      port: 6101

logging:
  level: INFO
  appenders:
    - type: console

# GitLab OAuth Configuration
# Update these values in your .env file
gitlab:
  host: ${GITLAB_HOST:-gitlab.com}
  appId: ${GITLAB_APP_ID}
  appSecret: ${GITLAB_APP_SECRET}
  redirectURI: http://localhost:6100/api/auth/callback

# MongoDB connection for session storage
mongodb:
  uri: mongodb://admin:admin@mongodb:27017/legend?authSource=admin
  database: legend
  sessionsCollection: sessions

# Project configuration
projectStructure:
  projectCreation:
    groupIdPattern: "^org\\.finos\\.legend\\..+"
    artifactIdPattern: "^[a-z][a-z0-9_]*$"

# Authentication
auth:
  enabled: false  # Set to true when GitLab OAuth is configured
  principal:
    property: username