apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-sdlc
  namespace: legend
  labels:
    app: legend-sdlc
    component: sdlc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legend-sdlc
  template:
    metadata:
      labels:
        app: legend-sdlc
        component: sdlc
    spec:
      containers:
      - name: legend-sdlc
        image: finos/legend-sdlc-server:0.195.0
        ports:
        - containerPort: 6100
        - containerPort: 6101
        env:
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms1g"
        - name: LEGEND_SDLC_URL
          valueFrom:
            configMapKeyRef:
              name: legend-config
              key: LEGEND_SDLC_URL
        - name: GITLAB_APP_ID
          valueFrom:
            secretKeyRef:
              name: gitlab-oauth
              key: GITLAB_APP_ID
        - name: GITLAB_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: gitlab-oauth
              key: GITLAB_APP_SECRET
        - name: GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-oauth
              key: GITLAB_HOST
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 6100
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 6100
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: legend-sdlc
  namespace: legend
  labels:
    app: legend-sdlc
spec:
  type: ClusterIP
  ports:
  - port: 6100
    targetPort: 6100
    protocol: TCP
    name: http
  - port: 6101
    targetPort: 6101
    protocol: TCP
    name: https
  selector:
    app: legend-sdlc
