apiVersion: apps/v1
kind: Deployment
metadata:
  name: legend-sdlc
spec:
  template:
    spec:
      containers:
      - name: legend-sdlc
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx384m -XX:MaxRAMPercentage=75.0"